### PR TITLE
Fix fsync fd, fd leak and export some useful method

### PR DESCRIPTION
**Pull request by prife**
1. fix fsync fd > 256
2. close connection fd in ListDevices and ReadPair
3. return error when EnableSSL failed
4. export dtx.decodeAuxiliary for custom use

### CODE REVIEW

**Comment by kkuehl** [comment]
The file descriptor should not be 0, 1, or 2.

**Comment by danielpaulus** [comment]
hey @prife  sorry for the late response, I was hacking on activation, erasing and supervising devices and finally got it done. It caused some conflicts with your PR. Would you be so kind and resolve those?
Thank you so much for contributing to go-iOS :-)

**Comment by prife** [comment]
> 

Got it, I will fix confilcts today.

**Comment by prife** [comment]
> hey @prife sorry for the late response, I was hacking on activation, erasing and supervising devices and finally got it done. It caused some conflicts with your PR. Would you be so kind and resolve those? Thank you so much for contributing to go-iOS :-)

Hi dainel, I've already fix the PR's conflict, now it works with the latest code

**Review by danielpaulus — APPROVED** [review]
Nice!

**Pull request merged**
