### PR TITLE
Format codebase with `gofmt` and enforce it in GitHub Actions

### LINKED ISSUE #232: Standarize and enforce code formatting
It'd be nice if the project used (thus, enforced) standardized code formatting, e.g with a tool such as `gofmt` (or even better, `gofumpt`, [which is a stricter version and widely used variant of `gofmt`](https://github.com/mvdan/gofumpt)).

**Describe the solution you'd like**

Format whole code with a formatted and enforce consistent code formatting for new PRs.

### PR DESCRIPTION
**Pull request by bartekpacia**
Fixes #232. More context in there as well :)

### CODE REVIEW

**Comment by shamanec** [comment]
I personally don't like the way it changed permissions notations to `0o777` but other than that looking good to me. Since this is a major change and judging by the failing unit tests it seems to enforces Go 1.18, I am a bit hesitant to merge it - @danielpaulus we need you :D

**Comment by bartekpacia** [comment]
@shamanec Using the `0o` prefix comes from `gofumpt`, and I think it makes it easier to see octal numbers :)

I bumped the minimum Go version to 1.18, let's see if tests pass.

**Comment by bartekpacia** [comment]
@danielpaulus @shamanec Used `gofmt` instead of `gofumpt`, kindly review :)

**Comment by nanoscopic** [comment]
Required Go version should not be bumped higher unless there is a need to do use a specific library in the codebase requiring it. Why was the version bumped?

Also agreed that permissions should not be modified to 777.

**Comment by bartekpacia** [comment]
> Also agreed that permissions should not be modified to 777.

Are they?

**Review by danielpaulus — APPROVED** [review]

**Comment by bartekpacia** [comment]
Once I fix the merge conflict, @danielpaulus this PR be merged?

**Comment by bartekpacia** [comment]
@danielpaulus I fixed the merge conflicts. I also went through all the changed files once again to make sure that only the formatting was changed, nothing else.

**Comment by danielpaulus** [comment]
> @danielpaulus I fixed the merge conflicts. I also went through all the changed files once again to make sure that only the formatting was changed, nothing else.

I will merge it in a bit. I am prototyping something to finally get real devices into the CI for proper testing.

**Review by danielpaulus — APPROVED** [review]

**Pull request merged**
