### PR TITLE
feat: Polish and fix the NPM package

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
These are preparation steps needed to include this tool into appium-xcuitest-driver dist.

The list of changes made in this PR:
- A "fat" binary is now created for macOS, which supports both arm64 and x64 architectures
- A proper symlink to the go-ios binary is created upon package install. index.js acts as a proxy for the symlink, whose main purpose is to match (and cache) the current platform needed to run the binary (actually the target binary path) and to act as an execution forwarder.
- Added README, so we could properly reflect the package info at https://www.npmjs.com/package/go-ios
- Limited the package to Node 18/ Npm 8 and later versions

### CODE REVIEW

**Comment by shamanec** [comment]
My knowledge on npm is limited but I would say it looks good to me, can't wait to run Appium with `go-ios` out of the box :D

**Review by shamanec — APPROVED** [review]

**Review by KazuCocoa — APPROVED** [review]

**Comment by mykola-mokhnach** [comment]
@danielpaulus Is there any chance for this PR to be merged soon?

**Review by danielpaulus — APPROVED** [review]
Thanks!

**Comment by danielpaulus** [comment]
Looks good to me!

**Comment by mykola-mokhnach** [comment]
> Looks good to me!

Thanks. Would it be possible to also reenable the automatic package publishing? The last one has been released almost half a year ago

**Pull request merged**
