### PR TITLE
Add userspace port CLI option

### PR DESCRIPTION
**Pull request by shamanec**
* When trying to run a command while manually supplying `rsd-port` and `address` and using userspace tunnels, also the userspace tunnel port has to be supplied or it doesn't work

### CODE REVIEW

**Comment by danielpaulus** [comment]
@dmissmann  can you take a look?

**Review by dmissmann — COMMENTED** [review]
Not sure if I understand why there can be a problem. When `rsd-port` and `address` are provided we are pointing to a tunnel that is not a userspace tunnel (for example I usually use it when I want to connect to the tunnel that is opened by MacOS). Why should there be a userspace tunnel at the same time?

**Comment by shamanec** [comment]
> Not sure if I understand why there can be a problem. When `rsd-port` and `address` are provided we are pointing to a tunnel that is not a userspace tunnel (for example I usually use it when I want to connect to the tunnel that is opened by MacOS). Why should there be a userspace tunnel at the same time?

My use case was that I needed finer control over tunnels so I was starting a tunnel per device using the module but then I wanted to run a command using the CLI providing `rsd-port` and `address` - but it doesn't work if the tunnel is a userspace tunnel. In the end I resolved it by using the modules everywhere around my app instead of using the CLI so I don't much care now if this gets merged. It might be good if someone wants finer control or is testing something out

**Comment by dmissmann** [comment]
> > Not sure if I understand why there can be a problem. When `rsd-port` and `address` are provided we are pointing to a tunnel that is not a userspace tunnel (for example I usually use it when I want to connect to the tunnel that is opened by MacOS). Why should there be a userspace tunnel at the same time?
> 
> My use case was that I needed finer control over tunnels so I was starting a tunnel per device using the module but then I wanted to run a command using the CLI providing `rsd-port` and `address` - but it doesn't work if the tunnel is a userspace tunnel. In the end I resolved it by using the modules everywhere around my app instead of using the CLI so I don't much care now if this gets merged. It might be good if someone wants finer control or is testing something out

ah ok, got it. and since it's an optional parameter it's perfectly fine 👍

**Review by dmissmann — APPROVED** [review]

**Comment by danielpaulus** [comment]
LGTM, Thanks Nikola :-D

**Pull request merged**
